### ISSUE TITLE
O sistema não esta verificando quantos alunos estão sendo cadastrados.

### ISSUE THREAD

**Issue by Jorgemartin2** [BrenoUtimura/Cadastro-Aluno#1]
## <div align="center">CASO</div>

**Foi definido no começo da função MAIN o máximo de 50 registros, só que não faz a verificação de quantos registros estão sendo cadastrados.**

## <div align="center">
**Como pode ver abaixo, não é feita nenhuma verificação na MAIN e nem na função de cadastro.**
<br>
![image](https://github.com/user-attachments/assets/45202e0d-5b06-4c8a-a807-718d7e16146d)
<br>
**Função de cadastro**
<br>
![image](https://github.com/user-attachments/assets/e13e4720-665f-40d0-a4ee-6d2508b6345d)
<br>
**Aqui esta uma possivel solução pra esse tipo de situação, mas essa verificação também pode ser melhorada.**
<br>
![image](https://github.com/user-attachments/assets/0104b4bd-905a-4025-868d-6d4c7309bd90)
</div>

**QUALQUER DUVIDA ESTOU A DISPOSIÇÃO!**

**Comment by BrenoUtimura** [comment]
Opa Jorge, Tudo bem?

Sobre o tamanho limite do vetor aluno[50], será modificado para a utilização da função malloc para alocação de memória dinâmicamente, então irei o tamanho do vetor será de forma dinâmica.

Mas adorei a sugestão para poder verificar de quando o limite máximo de cadastro é atingido. 

Vou realizar a implementação sobre isso para que haja uma melhor forma de resposta do sistema para quando há esse tipo de situação!

Muito Obrigado  😁
